# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    # Xcode'da build numarasını artır
    increment_build_number(
      xcodeproj: "cicdTestApp.xcodeproj"
    )

    # Uygulamayı build et
    build_app(
      scheme: "cicdTestApp",
      export_method: "app-store"
    )

    # TestFlight'a yükle
    upload_to_testflight
  end
end
